import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import Providers from './providers'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-50 dark:bg-slate-950">
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
